version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sh1057!  # 비밀번호
      MYSQL_DATABASE: nailart_db   # 사용할 DB 이름
      MYSQL_USER: user             # 선택적 사용자 계정
      MYSQL_PASSWORD: userpass     # 사용자 계정 비밀번호
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
